export { default as HomePage } from "./home";
export { default as AuthPage } from "./auth";
export { default as NotFoundPage } from "./not-found";
export { default as PostDetailPage } from "./post-detail";
export { default as ContactPage } from "./contact";
export { default as AboutPage } from "./about";
export { default as PostsPage } from "./posts";
export { default as SuccessPage } from "./success";
export { default as RecoveryAccountPage } from "./recovery-account";
